"""empty message

Revision ID: 155b5194ef77
Revises: a43c677bfbb2
Create Date: 2024-06-26 10:55:36.797756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155b5194ef77'
down_revision = 'a43c677bfbb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=False))
        batch_op.drop_constraint('shopping_cart_user_client_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user_client', ['client_id'], ['id'])
        batch_op.drop_column('user_client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shopping_cart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_client_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('shopping_cart_user_client_id_fkey', 'user_client', ['user_client_id'], ['id'])
        batch_op.drop_column('total')
        batch_op.drop_column('quantity')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
