"""empty message

Revision ID: a43c677bfbb2
Revises: 922c47e52037
Create Date: 2024-06-24 11:06:35.227800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43c677bfbb2'
down_revision = '922c47e52037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_foreign_key(None, 'user_artist', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('client_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
